apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: member-svc-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: member-svc
        env: prod
    spec:
      containers:
        - name: member-svc
          image: hetao/member-svc
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
          volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/crm
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  selector:
    app: member-svc
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer